server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.32.124.86:13306/laptech
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: sunflynf@gmail.com
    password: ezwealdkqsasicqg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true